
services:
    php-8.4:
        image: php:8.4-fpm-alpine3.20
        container_name: php-8.3
        build:
            context: ../
            dockerfile: ./.docker/php/Dockerfile
        volumes:
            - ../:/app
        networks:
            backend:

networks:
    backend:

volumes:
    mysql-data:
    cache:
        driver: local